defaults:
  - _self_

env_name: CarRacing-v1

# env paramters
horizon: 1024 # length of rollouts during experience collection 
state_type: observation # observation or vector
action_type: continuous # continuous or discrete

# algo parameters
num_steps: 1000
save_interval: 1000
test_interval: 100

# algo parameters
lr: 1e-3
lr_a: 3e-4
lr_c: 1e-3
