defaults:
  - _self_

env_name: CartPole-v1

# env paramters
horizon: 256 # length of rollouts during experience collection 
action_type: discrete # conditional or discrete


# algo parameters
num_steps: 700
save_interval: 700
lr: 1e-3
lr_a: 1e-3
lr_c: 1e-3
