defaults:
  - _self_

env_name: InvertedDoublePendulum-v4
run_name: ${now:%Y-%m-%d}_${now:%H%M%S}

# env paramters
horizon: 256 # length of rollouts during experience collection 
action_type: continuous # conditional or discrete

# algo parameters
lr: 1e-3
lr_a: 3e-4
lr_c: 1e-3
