defaults:
  - _self_

env_name: Pendulum-v1
run_name: ${now:%Y-%m-%d}_${now:%H%M%S}

# env paramters
horizon: 256 # length of rollouts during experience collection 
action_type: continuous # conditional or discrete

# algo parameters
num_steps: 700
save_interval: 700
lr: 1e-3
lr_a: 1e-3
lr_c: 1e-3
